In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\Krishna\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\sessions\DA88CEF746E60E093EB37B3A0AD1CCC13C54AD63\transfers\2026-26\Churn_Modelling_with_nulls.csv")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602.0,Hargrave,619.0,France,Female,NaN,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,2,15647311.0,Hill,608.0,Spain,Female,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,3,15619304.0,Onio,502.0,France,Female,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,4,15701354.0,Boni,699.0,France,Female,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,5,15737888.0,Mitchell,850.0,Spain,Female,43.0,NaN,125510.82,1.0,1.0,1.0,79084.10,0.0

In [4]:
df.shape

(10000, 14)

In [7]:
df.isnull().sum()

RowNumber            0
CustomerId         495
Surname            533
CreditScore        516
Geography          502
Gender             481
Age                519
Tenure             514
Balance            497
NumOfProducts      486
HasCrCard          497
IsActiveMember     497
EstimatedSalary    481
Exited             478
dtype: int64

In [8]:
df_num_col=df.select_dtypes(include=['int','float'])

In [9]:
df_obj_col=df.select_dtypes(include=['object'])

In [10]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602.0,Hargrave,619.0,France,Female,NaN,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,2,15647311.0,Hill,608.0,Spain,Female,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,3,15619304.0,Onio,502.0,France,Female,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,4,15701354.0,Boni,699.0,France,Female,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,5,15737888.0,Mitchell,850.0,Spain,Female,43.0,NaN,125510.82,1.0,1.0,1.0,79084.10,0.0

In [11]:
df_num_col.drop(columns=['RowNumber'],inplace=True)

In [12]:
df_num_col.head()

,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602.0,619.0,NaN,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,15647311.0,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,15619304.0,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,15701354.0,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,15737888.0,850.0,43.0,NaN,125510.82,1.0,1.0,1.0,79084.10,0.0

In [13]:
df_num_col.isnull().sum()

CustomerId         495
CreditScore        516
Age                519
Tenure             514
Balance            497
NumOfProducts      486
HasCrCard          497
IsActiveMember     497
EstimatedSalary    481
Exited             478
dtype: int64

In [14]:
df_num_col.drop('CustomerId', axis=1, inplace=True)

In [15]:
df_num_col.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619.0,NaN,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,850.0,43.0,NaN,125510.82,1.0,1.0,1.0,79084.10,0.0

In [16]:
df_num_col.isnull().sum()

CreditScore        516
Age                519
Tenure             514
Balance            497
NumOfProducts      486
HasCrCard          497
IsActiveMember     497
EstimatedSalary    481
Exited             478
dtype: int64

In [17]:
num_list=list(df_num_col.columns)

In [18]:
num_list

['CreditScore',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Exited']

In [19]:
for i in num_list:
    df_num_col[i]=df_num_col[i].replace(np.nan,df_num_col[i].median())

In [20]:
df_num_col.isnull().sum()

CreditScore        0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [21]:
df_num_col.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619.0,37.0,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,850.0,43.0,5.0,125510.82,1.0,1.0,1.0,79084.10,0.0

# Cat Cols

In [22]:
df_obj_col.head()

    Surname Geography  Gender
0  Hargrave    France  Female
1      Hill     Spain  Female
2      Onio    France  Female
3      Boni    France  Female
4  Mitchell     Spain  Female

In [23]:
df_obj_col.drop(columns=['Surname'], inplace=True)

In [24]:
df_obj_col.head()

  Geography  Gender
0    France  Female
1     Spain  Female
2    France  Female
3    France  Female
4     Spain  Female

In [25]:
df_obj_col['Geography'].value_counts()

Geography
France     4747
Germany    2381
Spain      2370
Name: count, dtype: int64

In [26]:
df_obj_col['Gender'].value_counts()

Gender
Male      5191
Female    4328
Name: count, dtype: int64

In [27]:
df_obj_col.isnull().sum()

Geography    502
Gender       481
dtype: int64

In [28]:
df_obj_col['Geography']=df_obj_col['Geography'].replace(np.nan,df_obj_col['Geography'].mode()[0])

In [29]:
df_obj_col['Gender']=df_obj_col['Gender'].replace(np.nan,df_obj_col['Gender'].mode()[0])

In [30]:
df_obj_col.isnull().sum()

Geography    0
Gender       0
dtype: int64

In [31]:
Geography_encoded = pd.get_dummies(df_obj_col['Geography'],prefix= 'Geography',drop_first=True,dtype=int)

df_obj_col = df_obj_col.drop(columns=['Geography'])

df_obj_col = pd.concat([df_obj_col,Geography_encoded], axis= 1)

In [32]:
Gender_encoded = pd.get_dummies(df_obj_col['Gender'],prefix= 'Gender',drop_first=True,dtype=int)

df_obj_col = df_obj_col.drop(columns=['Gender'])

df_obj_col = pd.concat([df_obj_col,Gender_encoded], axis= 1)

In [33]:
df_obj_col.head()

   Geography_Germany  Geography_Spain  Gender_Male
0                  0                0            0
1                  0                1            0
2                  0                0            0
3                  0                0            0
4                  0                1            0

In [34]:
df_num_col.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619.0,37.0,2.0,0.00,1.0,1.0,1.0,101348.88,1.0
1,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0
2,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0
3,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0
4,850.0,43.0,5.0,125510.82,1.0,1.0,1.0,79084.10,0.0

# Concat both cat and num cols

In [35]:
df2 = pd.concat([df_num_col,df_obj_col],axis=1)

In [36]:
df2.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619.0,37.0,2.0,0.00,1.0,1.0,1.0,101348.88,1.0,0,0,0
1,608.0,41.0,1.0,83807.86,1.0,0.0,1.0,112542.58,0.0,0,1,0
2,502.0,42.0,8.0,159660.80,3.0,1.0,0.0,113931.57,1.0,0,0,0
3,699.0,39.0,1.0,0.00,2.0,0.0,0.0,93826.63,0.0,0,0,0
4,850.0,43.0,5.0,125510.82,1.0,1.0,1.0,79084.10,0.0,0,1,0

In [37]:
X=df2.drop(columns=['Exited']) 
y=df2['Exited']

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=12)

In [40]:
X_train

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
9254,686.0,32.0,6.0,0.00,2.0,1.0,1.0,179093.26,0,0,1
1561,632.0,42.0,4.0,119624.60,2.0,1.0,1.0,195978.86,1,0,1
1670,559.0,24.0,3.0,114739.92,1.0,1.0,0.0,85891.02,0,1,1
6087,561.0,27.0,9.0,135637.00,1.0,1.0,0.0,153080.40,0,0,0
6669,517.0,56.0,9.0,142147.32,1.0,0.0,1.0,39488.04,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
5734,768.0,54.0,8.0,69712.74,1.0,1.0,1.0,69381.05,0,0,1
5191,682.0,58.0,1.0,0.00,1.0,1.0,1.0,706.50,0,0,0
5390,735.0,38.0,1.0,0.00,3.0,0.0,1.0,92220.12,0,0,0
860,667.0,43.0,8.0,190227.46,1.0,1.0,1.0,97508.04,0,0,1
7270,697.0,51.0,5.0,147910.30,1.0,1.0,1.0,53581.14,1,0,1

#  Scaling

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
ss= StandardScaler()

In [43]:
X_train_scale=pd.DataFrame(ss.fit_transform(X_train),columns=X_train.columns)

In [44]:
X_test_scale=pd.DataFrame(ss.fit_transform(X_test),columns=X_test.columns)

In [45]:
X_test_scale

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,-0.536624,-0.193045,-0.706067,0.295422,0.853669,-1.613569,-1.096651,-1.016074,1.794271,-0.546536,0.873881
1,-0.251845,0.398967,-1.402557,-1.292949,0.853669,0.619744,0.911867,0.839223,-0.557329,-0.546536,0.873881
2,0.054029,0.497636,-0.357822,-1.292949,0.853669,0.619744,-1.096651,-0.718545,-0.557329,1.829707,-1.144320
3,-1.485888,1.977667,1.035159,0.664031,0.853669,0.619744,0.911867,1.270279,1.794271,-0.546536,0.873881
4,-0.916330,-1.179733,0.686914,0.760012,-0.858806,0.619744,0.911867,0.276741,-0.557329,1.829707,-1.144320
...,...,...,...,...,...,...,...,...,...,...,...
1995,-0.473340,1.385655,-0.009577,0.321040,-0.858806,-1.613569,0.911867,-0.958425,1.794271,-0.546536,-1.144320
1996,-0.399508,-1.377071,1.731649,-1.292949,-0.858806,-1.613569,0.911867,0.192046,-0.557329,-0.546536,0.873881
1997,0.054029,0.793642,0.686914,-1.292949,-0.858806,0.619744,-1.096651,-1.165346,-0.557329,-0.546536,-1.144320
1998,0.475924,-0.982395,-0.357822,-1.292949,-0.858806,0.619744,-1.096651,-0.395797,-0.557329,-0.546536,0.873881
1999,-0.199108,0.004292,-1.402557,0.601440,-0.858806,0.619744,0.911867,0.152651,1.794271,-0.546536,0.873881

In [51]:
import tensorflow

In [52]:
from tensorflow import keras

In [53]:
from tensorflow.keras import Sequential

In [54]:
from tensorflow.keras.layers import Dense

In [55]:
model=Sequential()

In [56]:
model.add(Dense(3,activation='sigmoid', input_dim=11))

C:\Users\rajan\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [57]:
model.add(Dense(1,activation='sigmoid'))

In [58]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 3)                   │              36 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.compile(loss='binary_crossentropy',optimizer='adam')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [60]:
model.fit(X_train_scale,y_train,epochs=5)

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 0.6708
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - loss: 0.5584
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.5028
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - loss: 0.4765
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - loss: 0.4627

In [62]:
predicted_values=model.predict(X_test_scale)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step

In [64]:
y_pred=np.where(predicted_values >0.5,1,0)

In [65]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], shape=(2000, 1))

In [66]:
from sklearn.metrics import accuracy_score

In [67]:
accuracy_score(y_test,y_pred)

0.8175